import './globals.css'
import Header from '@/components/ui/Header'
import Session from '@/utils/Session'
import ReactQueryProvider from '@/utils/ReactQueryProvider'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Session>
          <ReactQueryProvider>
            <Header />
            <div className="relative w-full max-w-4xl p-4 mx-auto">{children}</div>
          </ReactQueryProvider>
        </Session>
      </body>
    </html>
  )
}
