import './globals.css'
import Header from '@/components/server/Header'
import Session from '@/utils/Session'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Session>
          <Header />
          <div className="w-full max-w-4xl p-4 mx-auto">{children}</div>
        </Session>
      </body>
    </html>
  )
}
